### REGISTER
# email - unique, required ;  password  - required ; first_name - required ; last_name : optional
POST http://localhost:8000/api/user/register/
Content-Type: application/json

{"password":"jeski" , "email":"jeski@gmail.com"  , "first_name":"jhon" , "last_name":""}

### LOGIN 
# email - required ; password - required 
POST http://localhost:8000/api/user/login/
Content-Type: application/json

{"email":"jeski@gmail.com" , "password":"jeski" }

### TEST
# returns ID of user upon sucessfull request
GET http://localhost:8000/api/test/protect/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjM3NTI0LCJpYXQiOjE3MTQwMjE1MjQsImp0aSI6ImQ4M2Y0ODkwNWVmNjQxNDBhMzgwMTQwY2YzMjY3ZDA0IiwiZW1haWwiOiJqZXNraUBnbWFpbC5jb20ifQ.RmIqhh_J1R09NxuCfppsustCGB-80jhvKwfH37joem8
### NOTES
#returns all the notes of a user ; protected route
GET  http://localhost:8000/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA0MzAzLCJpYXQiOjE3MTM5ODgzMDMsImp0aSI6ImNhZjNmZTkyNTI0MzQ0Y2FhNzRkYjI5YjE5OTM1NmY0IiwiZW1haWwiOiJrczFAZ21haWwuY29tIn0.a-zb5LEcugbHe6mTsEVA8gZ9hi1donm1H-noeaTbxlY
### NOTES BY ID
GET  http://localhost:8000/api/notes/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA0MzAzLCJpYXQiOjE3MTM5ODgzMDMsImp0aSI6ImNhZjNmZTkyNTI0MzQ0Y2FhNzRkYjI5YjE5OTM1NmY0IiwiZW1haWwiOiJrczFAZ21haWwuY29tIn0.a-zb5LEcugbHe6mTsEVA8gZ9hi1donm1H-noeaTbxlY

### CREATE NOTES BY USER
POST  http://localhost:8000/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA0MzAzLCJpYXQiOjE3MTM5ODgzMDMsImp0aSI6ImNhZjNmZTkyNTI0MzQ0Y2FhNzRkYjI5YjE5OTM1NmY0IiwiZW1haWwiOiJrczFAZ21haWwuY29tIn0.a-zb5LEcugbHe6mTsEVA8gZ9hi1donm1H-noeaTbxlY

{"title":"nights are young" , "content":"dsahdj"}
### UPDATES NOTES
PUT   http://localhost:8000/api/notes/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA0MzAzLCJpYXQiOjE3MTM5ODgzMDMsImp0aSI6ImNhZjNmZTkyNTI0MzQ0Y2FhNzRkYjI5YjE5OTM1NmY0IiwiZW1haWwiOiJrczFAZ21haWwuY29tIn0.a-zb5LEcugbHe6mTsEVA8gZ9hi1donm1H-noeaTbxlY

{"title":"nights are old" , "content":"fucked me"}

### DELETES NOTES
DELETE  http://localhost:8000/api/notes/3/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA0MzAzLCJpYXQiOjE3MTM5ODgzMDMsImp0aSI6ImNhZjNmZTkyNTI0MzQ0Y2FhNzRkYjI5YjE5OTM1NmY0IiwiZW1haWwiOiJrczFAZ21haWwuY29tIn0.a-zb5LEcugbHe6mTsEVA8gZ9hi1donm1H-noeaTbxlY
